# Generated by Django 5.1.1 on 2024-09-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_title',
            new_name='notification_message',
        ),
    ]
