# Generated by Django 5.1.1 on 2024-09-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0003_rename_notification_title_notification_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_message',
            new_name='notification_title',
        ),
    ]
